# -*- coding: utf-8 -*-
"""PYTHON-PROJECT

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1w33zi0AsixSde7VLHIktI6QVdsvj-rg6
"""

import plotly.graph_objs as go

def get_user_data():
    try:
        # Get x and y values from the user
        x_data = input("Enter x values (comma-separated): ").split(',')
        y_data = input("Enter y values (comma-separated): ").split(',')

        # Convert input strings to floats
        x_data = [float(x.strip()) for x in x_data]
        y_data = [float(y.strip()) for y in y_data]

        return x_data, y_data

    except ValueError:
        print("Error: Please enter valid numbers for x and y values.")
        return None, None

def get_plot_type():
    plot_types = {"1": "scatter", "2": "line", "3": "bar"}
    print("Select plot type:")
    print("1: Scatter")
    print("2: Line")
    print("3: Bar")

    plot_type = input("Enter the number corresponding to your choice: ")
    return plot_types.get(plot_type, "scatter")

def create_plot(x_data, y_data, plot_type):
    if plot_type == "scatter":
        trace = go.Scatter(x=x_data, y=y_data, mode='markers')
    elif plot_type == "line":
        trace = go.Scatter(x=x_data, y=y_data, mode='lines')
    elif plot_type == "bar":
        trace = go.Bar(x=x_data, y=y_data)
    else:
        trace = go.Scatter(x=x_data, y=y_data, mode='markers')  # Default to scatter

    # Create layout
    layout = go.Layout(
        title=f'Interactive {plot_type.capitalize()} Plot',
        xaxis=dict(title='X-axis Label'),
        yaxis=dict(title='Y-axis Label')
    )

    # Create figure
    fig = go.Figure(data=[trace], layout=layout)

    # Display the plot
    fig.show()

def main():
    x_data, y_data = get_user_data()
    if x_data is not None and y_data is not None:
        plot_type = get_plot_type()
        create_plot(x_data, y_data, plot_type)

if __name__ == "__main__":
    main()